root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/server ./main.go"
  bin = "tmp/server"
  include_ext = ["go"]
  exclude_dir = ["tmp", "vendor", ".git"]
  delay = 1000

[log]
  time = true
